runtime: nodejs18

service: redirect-server
entrypoint: node src/app.js

handlers:
  - url: /favicon\.ico
    static_files: public/favicon.ico
    upload: favicon\.ico
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
