runtime: nodejs18

entrypoint: NODE_ENV=production node src/app.js

handlers:
  - url: /favicon\.ico
    static_files: src/public/favicon.ico
    upload: favicon\.ico
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
