runtime: nodejs18

entrypoint: node src/app.js

env_variables:
  NODE_ENV: "production"

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.75
  min_instances: 0
  max_instances: 3
  min_pending_latency: 30ms
  max_pending_latency: automatic