const FIVE_MINUTES_IN_SECONDS = 5 * 60;
const TWENTY_MINUTES_IN_SECONDS = 20 * 60;
const HALF_AN_HOUR_IN_SECONDS = 30 * 60;

module.exports = {
  FIVE_MINUTES_IN_SECONDS,
  TWENTY_MINUTES_IN_SECONDS,
  HALF_AN_HOUR_IN_SECONDS,
};
